version: "3.8"

services:
  root:
    build: .
    image: root:latest
    ports:
      - 4080:4080
  zero:
    image: dgraph/dgraph:master
    volumes:
      - /tmp/data:/dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:master
    volumes:
      - /tmp/data:/dgraph
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist 172.20.0.1,172.21.0.1
